"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle    T_n=n(n+1)/2    1, 3, 6, 10, 15, ...
Pentagonal  P_n=n(3n−1)/2   1, 5, 12, 22, 35, ...
Hexagonal   H_n=n(2n−1)     1, 6, 15, 28, 45, ..

It can be verified that T_285 = P_165 = H_143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
"""


import itertools
from lib.sequence import hexagonal, increasing_seq_cache, pentagonal, triangle


def solve_problem() -> int:
    is_triangular = increasing_seq_cache(triangle)
    is_pentagonal = increasing_seq_cache(pentagonal)

    for n in itertools.count(144):
        h = hexagonal(n)
        if is_triangular(h) and is_pentagonal(h):
            return h

    raise AssertionError()
